version: '2.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=byondtest
      - MYSQL_USER=byond
      - MYSQL_PASSWORD=mypassword
    ports:
      - "33061:3306"

  tomcat:
    build: tomcat
    working_dir: /usr/local/tomcat
    command: catalina.sh jpda run
    links:
      - mysql
    environment:
      JPDA_ADDRESS: 8000
      JPDA_TRANSPORT: dt_socket
    expose:
      - "8080"



  nginx:
    build: nginx
    command: nginx -g "daemon off;"
    links:
      - tomcat
    container_name: nginx
    depends_on:
      tomcat:
        condition: service_started
    ports:
      - "5000:80"
