apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: retwisj
  name: retwisj
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: retwisj
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50