apiVersion: v1
kind: Service
metadata:
  labels:
    app: retwisj
  name: retwisj
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: retwisj
  type: NodePort
