before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
 # - unit-tests
  - docker build

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build spring:
    stage: build
    image: gradle:jdk12
    script:
        - cd $CI_PROJECT_DIR/microservice/challenge-1/backend
        - gradle clean build -x test
        - ls -la $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs
    artifacts:
      paths:
        - $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/backend-latest.jar
      expire_in: 10 minutes
    tags:
      - gitlab-org

.unit test:
    stage: unit-tests
    image: gradle:jdk12
    script:
        - cd $CI_PROJECT_DIR/microservice/challenge-1/backend
        - gradle unitTest

docker build:
    stage: docker build
    image: docker:stable
    services:
      - docker:dind
    variables:
      DOCKER_DRIVER: overlay2
      #SHARED_PATH: /builds/shared/$CI_PROJECT_PATH
    script:
      - pwd
      - ls -la /builds/stormbringerdp/amaze-us/
      - mkdir -p /builds/stormbringerdp/amaze-us/build/
      - ls -la /builds/stormbringerdp/amaze-us/build
      - ls -la $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/
      - cp $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/backend-latest.jar /builds/stormbringerdp/amaze-us/build/
      - cp $CI_PROJECT_DIR/microservice/challenge-1/backend/Dockerfile /builds/stormbringerdp/amaze-us/build/
      - ls -la /builds/stormbringerdp/amaze-us/build/
      - ls -la /builds/stormbringerdp/amaze-us/
      - docker build -t hren /builds/stormbringerdp/amaze-us/build/
      #- echo $CI_PROJECT_PATH
      #- mkdir -p ${SHARED_PATH}
      #- echo ${SHARED_PATH}
      #- cp $CI_PROJECT_DIR/microservice/challenge-1/backend/Dockerfile ${SHARED_PATH}/Dockerfile
      #- ls -la ${SHARED_PATH}
      #- docker run -v ${SHARED_PATH}:/mnt ubuntu ls /mnt
      #- ls -la ${SHARED_PATH}
      #- docker build -t hren ${SHARED_PATH}/
       #- docker build -t hren /builds/stormbringerdp/amaze-us/microservice/challenge-1/backend
       #- docker cp /builds/stormbringerdp/amaze-us/microservice/challenge-1/backend/
    #  - ls -la /builds/stormbringerdp/amaze-us/microservice/challenge-1/backend/build/libs/
    #  - ls -la $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/
     # - mkdir -p ${SHARED_PATH}
     # - cp $CI_PROJECT_DIR/microservice/challenge-1/backend/Dockerfile ${SHARED_PATH}/Dockerfile
     # - docker run -v ${SHARED_PATH}:/mnt ubuntu ls /mnt
      #- docker run -v $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/:/mnt
      #- docker build -t my-docker-image $CI_PROJECT_DIR/microservice/challenge-1/backend
    tags:
      - docker

