before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
  - unit-tests

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build spring:
    stage: build
    image: gradle:jdk12
    script:
        - cd $CI_PROJECT_DIR/microservice/challenge-1/backend
        - gradle clean build -x test
        - ls -la $CI_PROJECT_DIR/build/libs/
    artifacts:
      paths:
        - $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/backend-latest.jar
      expire_in: 60 minutes

unit test:
    stage: unit-tests
    image: gradle:jdk12
    script:
        - cd $CI_PROJECT_DIR
        - gradle unitTest
