before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - build
 # - unit-tests
  - docker build

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build spring:
    stage: build
    image: gradle:jdk12
    script:
        - cd $CI_PROJECT_DIR/microservice/challenge-1/backend
        - gradle clean build -x test
        - ls -la $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs
    artifacts:
      paths:
        - $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/backend-latest.jar
      expire_in: 10 minutes

.unit test:
    stage: unit-tests
    image: gradle:jdk12
    script:
        - cd $CI_PROJECT_DIR/microservice/challenge-1/backend
        - gradle unitTest

docker build:
    stage: docker build
    image: docker:stable
    services:
      - docker:dind
    variables:
      DOCKER_DRIVER: overlay2

    script:
      - ls -la /builds/stormbringerdp/amaze-us/microservice/challenge-1/backend/build/libs/
      - ls -la $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/
      - docker run -v $CI_PROJECT_DIR/microservice/challenge-1/backend/build/libs/:/mnt
      - docker build -t my-docker-image $CI_PROJECT_DIR/microservice/challenge-1/backend

