version: '3.7'
services:
  postman:
    image: postman/newman_ubuntu1404
    command: run "https://www.getpostman.com/collections/4a0bf8d59b6cdbcad9c2"
    links:
       - booster:booster
    condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s