spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    database: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
    username: admin
    password: admin
    initialization-mode: never
server:
  servlet:
    context-path: "/api"
logging:
  level:
    ROOT: info
