version: 2
jobs:
  build:
    machine: true
    
    steps: # TODO 
      - run: 
          - name: BOOSTER - spawns the container and test
          - command: |
              cd booster/
              make docker-compose-up #TODO refactoring to show explicitly the test and the result
              sleep 5 #TODO ahahah find a better way
              make test
              make it-test

      - run:
          - name: CARGO - spawns the container and test
          - command: |
              cd cargo/
              make test
              make docker-compose-up #TODO refactoring to show explicitly the test and the result
              sleep 5 #TODO ahahah find a better way
              make it-test
              make ui-test
           - run:

      - name: STAGE2 - spawns the container and test
          - command: |
              cd cargo/
              make test

        

