version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:latest
    steps: # TODO we should see explicity the test, integration, ui test results 
      - setup_remote_docker
      - run:
          name: Love Boat docker-compose and circleci
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - run: 
          name: BOOSTER - spawns the container
          command: |
              cd microservice/challenge-3/booster/
              make docker-compose-up #TODO refactoring to show explicitly the test and the result
          background: true 
      
      - run: 
          name: BOOSTER -test
          command: |
              cd microservice/challenge-3/booster/
              sleep 5 #TODO ahahah find a better way
              make it-test
              make ui-test  
              docker ps -qa | xargs docker rm -f

      - run:
          name: CARGO - spawns the container and test
          command: |
              cd microservice/challenge-3/cargo/
              make test
              make docker-compose-up #TODO refactoring to show explicitly the test and the result
              sleep 5 #TODO ahahah find a better way
              make it-test
              make ui-test

      - run:
          name: STAGE2 - spawns the container and test
          command: |
              cd microservice/challenge-3/stage2/
              make test
      
      - run: 
          name: CHALLENGE-3 - spawns the container and test
          command: |
              cd microservice/challenge-3/
              make up-dev #TODO refactoring to show explicitly the test and the result
              sleep 5 #TODO ahahah find a better way
              make it-test

        

