version: 2
jobs:
  build:
    machine: true
    steps: # TODO we should see explicity the test, integration, ui test results 
      - checkout
      - run: 
          - name: BOOSTER - spawns the container and test
          - command: |
              cd microservice/challenge-3/booster/
              make docker-compose-up #TODO refactoring to show explicitly the test and the result
              sleep 5 #TODO ahahah find a better way
              make test
              make it-test
