apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 8000
  selector:
    app: frontend
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: challenge/frontend:latest
        name: frontend
        ports:
        - containerPort: 8080
          name: frontend-server

        # frontend -> userservice connection settings
        env:
          - name: USERSERVICE_HOST
            value: userservice
          - name: USERSERVICE_PORT
            value: 9000