version: "3"

services:
  test:
    container_name: test
    build:
      context: ./cargo
      dockerfile: app.dockerfile
      args:
        NODE_ENV: test
    environment:
      NODE_ENV: test
    ports:
      - "3000:3000"
    networks:
      - rocket-test-network
    command: ["test"]
    depends_on: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - rocket-test-network
    ports:
      - "27017:27017"
networks:
  rocket-test-network:
    driver: bridge
