version: '3.7'
services:
  haproxy:
     build: "haproxy"
     ports:
      - "80:80"
      - "8666:8666"
     links:
      - "booster:booster"
      - "cargodenuit:cargo"
     networks:
      - networks_challenge3
  booster:
    networks:
      - networks_challenge3
  cargodenuit:
    networks:
      - networks_challenge3
networks:
  networks_challenge3: