version: "3.7"
services:
  notebook:
    image: notebook:local
    container_name: spark_notebook
    build:
      context: ./notebooks
      dockerfile: Dockerfile
    volumes:
      - ../:/home/analytics/workspace
    ports:
      - "8001:8001"
    environment:
      - NOJUPYTER_ENABLE_LAB=0
    command: start-notebook.sh --ip=* --port 8001 --NotebookApp.notebook_dir=workspace/ --ResourceUseDisplay.track_cpu_percent=True --NotebookApp.token='' --NotebookApp.password=''
  ingest:
      image: ingest_tweets:local
      container_name: ingest_py_tweets
      build:
        context: ./ingest
        dockerfile: Dockerfile
      depends_on: 
        - kafka-broker
      volumes:
        - ../ingest:/home/analytics/workspace
        - ../tw_data:/home/analytics/workspace/data
      command: python3 /home/analytics/workspace/twitter_stream.py --to_kafka --output_path /home/analytics/workspace/data
  spark-master:
    build:
      context: ./spark-master
      dockerfile: Dockerfile
      args:
        PRE_TAG: bd-infra
    image: bd-infra-spark-master
    container_name: spark-master
    ports:
        - 8080:8080
        - 7077:7077
        - 4040:4040
    volumes:
      - shared-workspace:/opt/workspace
      - ../:/home/analytics/workspace
  spark-worker-1:
    build:
      context: ./spark-slave
      dockerfile: Dockerfile
      args:
        PRE_TAG: bd-infra
    image: bd-infra-spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2gb
    ports:
      - 8083:8081
    volumes:
      - shared-workspace:/opt/workspace
      - ../:/home/analytics/workspace
    depends_on:
      - spark-master
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    hostname:  by-zookeeper
    container_name: by-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka-broker:
    image: confluentinc/cp-kafka:6.1.1
    hostname: by-kafka-broker
    container_name: by-kafka-broker
    depends_on:
      -  zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'by-zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://by-kafka-broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
