spring:    
  application:
    name: getapp
  datasource:
    url: jdbc:mysql://remotemysql.com:3306/IVKMD9q7pZ
    username: IVKMD9q7pZ
    password: PiTDofgf3G
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate: 
      ddl-auto: none
    show-sql: false
    generate-ddl: true

server:
  port: ${PORT:0}

eureka: 
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int[1,999999]}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

management:
  security:
    enabled: false
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.cathedral: INFO
    org.springframework: ERROR